config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :historics
  resources :disappeareds
  resources :cities
  resources :parents
  resources :streets, only: :show

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :districts

  def to_s
    name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
  def to_s
    name
  end
end

app/models/disappeared.rb
class Disappeared < ApplicationRecord
 
  
  has_one_attached :avatar
  belongs_to :user
  belongs_to :street
  has_many :historics
  has_many :relations

  validates :name, presence: true
  validates :disappearance_date, presence: true
  validates :avatar, presence: true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
  has_many :streets

  def to_s
    name
  end
end

app/models/historic.rb
class Historic < ApplicationRecord
  belongs_to :disappeared
end

app/models/parent.rb
class Parent < ApplicationRecord
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :user
  belongs_to :disappeared
  belongs_to :parent
  has_many :relatives
end

app/models/relative.rb
class Relative < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities

  def to_s
    name
  end
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :historics
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :district
  has_many :disappeareds

  def to_s
    "#{district.city} - #{district.city.state}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relations
  has_many :disappeareds

  def to_s
    name
  end
end

app/controllers/historics_controller.rb
class HistoricsController < ApplicationController
  before_action :set_historic, only: [:show, :edit, :update, :destroy]

  # GET /historics
  # GET /historics.json
  def index
    @historics = Historic.all
  end

  # GET /historics/1
  # GET /historics/1.json
  def show
  end

  # GET /historics/new
  def new
    @historic = Historic.new
  end

  # GET /historics/1/edit
  def edit
  end

  # POST /historics
  # POST /historics.json
  def create
    @historic = Historic.new(historic_params)

    respond_to do |format|
      if @historic.save
        format.html { redirect_to @historic, notice: 'Historic was successfully created.' }
        format.json { render :show, status: :created, location: @historic }
      else
        format.html { render :new }
        format.json { render json: @historic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historics/1
  # PATCH/PUT /historics/1.json
  def update
    respond_to do |format|
      if @historic.update(historic_params)
        format.html { redirect_to @historic, notice: 'Historic was successfully updated.' }
        format.json { render :show, status: :ok, location: @historic }
      else
        format.html { render :edit }
        format.json { render json: @historic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historics/1
  # DELETE /historics/1.json
  def destroy
    @historic.destroy
    respond_to do |format|
      format.html { redirect_to historics_url, notice: 'Historic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historic
      @historic = Historic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historic_params
      params.require(:historic).permit(:description, :text, :disappeared_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/historics_helper.rb
module HistoricsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/historics/_form.html.erb
<%= simple_form_for(@historic) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :text %>
    <%= f.association :disappeared %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/historics/edit.html.erb
<h1>Editing Historic</h1>

<%= render 'form', historic: @historic %>

<%= link_to 'Show', @historic %> |
<%= link_to 'Back', historics_path %>

app/views/historics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historics</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Text</th>
      <th>Disappeared</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historics.each do |historic| %>
      <tr>
        <td><%= historic.description %></td>
        <td><%= historic.text %></td>
        <td><%= historic.disappeared %></td>
        <td><%= link_to 'Show', historic %></td>
        <td><%= link_to 'Edit', edit_historic_path(historic) %></td>
        <td><%= link_to 'Destroy', historic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historic', new_historic_path %>

app/views/historics/new.html.erb
<h1>New Historic</h1>

<%= render 'form', historic: @historic %>

<%= link_to 'Back', historics_path %>

app/views/historics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @historic.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @historic.text %>
</p>

<p>
  <strong>Disappeared:</strong>
  <%= @historic.disappeared %>
</p>

<%= link_to 'Edit', edit_historic_path(@historic) %> |
<%= link_to 'Back', historics_path %>