config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :historics
  resources :disappeareds
  resources :cities
  resources :parents
  resources :streets, only: :show

  root to: "home#index"
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :districts

  def to_s
    name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
  def to_s
    name
  end
end

app/models/disappeared.rb
class Disappeared < ApplicationRecord
 
  
  has_one_attached :avatar
  belongs_to :user
  belongs_to :street
  has_many :historics
  has_many :relations

  validates :name, presence: true
  validates :disappearance_date, presence: true
  validates :avatar, presence: true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
  has_many :streets

  def to_s
    name
  end
end

app/models/historic.rb
class Historic < ApplicationRecord
  belongs_to :disappeared
end

app/models/parent.rb
class Parent < ApplicationRecord
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :user
  belongs_to :disappeared
  belongs_to :parent
  has_many :relatives
end

app/models/relative.rb
class Relative < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities

  def to_s
    name
  end
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :historics
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :district
  has_many :disappeareds

  def to_s
    "#{district.city} - #{district.city.state}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relations
  has_many :disappeareds

  def to_s
    name
  end
end

app/controllers/disappeareds_controller.rb
class DisappearedsController < ApplicationController
  before_action :set_disappeared, only: [:show, :edit, :update, :destroy]
  include AuxiliarBusinessRules

  def index
    @disappeareds = Disappeared.all
  end

  def show
    render json: {disappeared: @disappeared}
  end

  def new
    @disappeared = Disappeared.new
  end

  def edit; end

  def create
    create_street_attributes(disappeared_params) unless find_street_attributes(disappeared_params)
    street = find_street_attributes(disappeared_params) ? Street.find_by(name: disappeared_params[:street]).id : create_street_attributes(disappeared_params).id
    @disappeared = Disappeared.new(disappeared_params.except(:street, :city, :uf, :district).merge(user_id: current_user.id, street_id: street, gender: false)) if params[:gender]
    @disappeared = Disappeared.new(disappeared_params.except(:street, :city, :uf, :district).merge(user_id: current_user.id, street_id: street)) unless params[:gender]

    respond_to do |format|
      if @disappeared.save
        format.html {redirect_to root_path, notice: "Desaparecido adicionado com sucesso"}
        format.json {render :show, status: :created, location: @disappeared}
      else
        format.html {render :new}
        format.json {render json: @disappeared.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @disappeared.update(disappeared_params)
        format.html {redirect_to @disappeared, notice: 'Disappeared was successfully updated.'}
        format.json {render :show, status: :ok, location: @disappeared}
      else
        format.html {render :edit}
        format.json {render json: @disappeared.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @disappeared.destroy
    respond_to do |format|
      format.html {redirect_to disappeareds_url, notice: 'Disappeared was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def set_disappeared
    @disappeared = Disappeared.find(params[:id])
  end

  def disappeared_params
    params.require(:disappeared).permit(:user_id, :name, :gender, :birthdate, :disappearance_date, :mother, :dad, :cep, :district, :street, :city, :uf, :avatar)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/disappeareds_helper.rb
module DisappearedsHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/historics_helper.rb
module HistoricsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/disappeareds/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <%= simple_form_for(@disappeared) do |f| %>

            <div class="row">
              <div class="col-md-12 text-center">
                <%= f.file_field :avatar, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-4">
                <div class="form-inputs">
                  <%= f.input :name, input_html: {class: "form-control"}, label: "Nome" %>
                </div>
              </div>
              <div class="col-md-2">
                <div class="form-inputs">
                  <%= f.input :gender, as: :select, collection: [["0", "Mulher"], ["1", "Homem"]], value_method: :first, label_method: :second, prompt: "Selecione", input_html: {class: "form-control"}, label: "Genero" %>
                </div>
              </div>
              <div class="col-md-3">
                <%= f.input :birthdate, input_html: {class: "form-control datepicker date", type: "text"}, label: "Data de Nascimento" %>
              </div>
              <div class="col-md-3">
                <%= f.input :disappearance_date, input_html: {class: "form-control datepicker date", type: "text"}, label: "Data do Desaparecimento" %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <%= f.input :mother, input_html: {class: "form-control"}, label: "Mãe" %>
              </div>
              <div class="col-md-6">
                <%= f.input :dad, input_html: {class: "form-control"}, label: "Pai" %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3">
                <div class="form-inputs">
                  <label for="disappeared_cep">Cep</label>
                  <input type="text" class="form-control cep" id="disappeared_cep" onkeyup="FindCEP(this.value)" required>
                </div>
              </div>
            </div>
            <div id="result_cep" class="row"></div>

            <div class='row'>
              <div class='col-md-12'>
                <div class='form-actions text-right'>
                  <%= submit_button("success", "fas fa-save", "Salvar") %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/disappeareds/edit.html.erb
<h1>Editing Disappeared</h1>

<%= render 'form', disappeared: @disappeared %>

<%= link_to 'Show', @disappeared %> |
<%= link_to 'Back', disappeareds_path %>

app/views/disappeareds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disappeareds</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Birthdate</th>
      <th>Disappearance date</th>
      <th>Street</th>
      <th>Mother</th>
      <th>Dad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disappeareds.each do |disappeared| %>
      <tr>
        <td><%= disappeared.user %></td>
        <td><%= disappeared.name %></td>
        <td><%= disappeared.gender %></td>
        <td><%= disappeared.birthdate %></td>
        <td><%= disappeared.disappearance_date %></td>
        <td><%= disappeared.street %></td>
        <td><%= disappeared.mother %></td>
        <td><%= disappeared.dad %></td>
        <td><%= link_to 'Show', disappeared %></td>
        <td><%= link_to 'Edit', edit_disappeared_path(disappeared) %></td>
        <td><%= link_to 'Destroy', disappeared, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disappeared', new_disappeared_path %>

app/views/disappeareds/new.html.erb
<%= render "form", disappeared: @disappeared %>

app/views/disappeareds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @disappeared.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @disappeared.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @disappeared.gender %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @disappeared.birthdate %>
</p>

<p>
  <strong>Disappearance date:</strong>
  <%= @disappeared.disappearance_date %>
</p>

<p>
  <strong>Street:</strong>
  <%= @disappeared.street %>
</p>

<p>
  <strong>Mother:</strong>
  <%= @disappeared.mother %>
</p>

<p>
  <strong>Dad:</strong>
  <%= @disappeared.dad %>
</p>

<%= link_to 'Edit', edit_disappeared_path(@disappeared) %> |
<%= link_to 'Back', disappeareds_path %>