config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :historics
  resources :disappeareds
  resources :cities
  resources :parents
  resources :streets, only: :show

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :districts

  def to_s
    name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
  def to_s
    name
  end
end

app/models/disappeared.rb
class Disappeared < ApplicationRecord
 
  
  has_one_attached :avatar
  belongs_to :user
  belongs_to :street
  has_many :historics
  has_many :relations

  validates :name, presence: true
  validates :disappearance_date, presence: true
  validates :avatar, presence: true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
  has_many :streets

  def to_s
    name
  end
end

app/models/historic.rb
class Historic < ApplicationRecord
  belongs_to :disappeared
end

app/models/parent.rb
class Parent < ApplicationRecord
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :user
  belongs_to :disappeared
  belongs_to :parent
  has_many :relatives
end

app/models/relative.rb
class Relative < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities

  def to_s
    name
  end
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :historics
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :district
  has_many :disappeareds

  def to_s
    "#{district.city} - #{district.city.state}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relations
  has_many :disappeareds

  def to_s
    name
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/historics_helper.rb
module HistoricsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/parents/_form.html.erb
<%= simple_form_for(@parent) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>